---
- hosts: all

  roles:
    ###
    ### Requirements
    ###
    - role: drive-mount
      tags:
        - drive-mount
        - mount-drives

    ###
    ### MergerFS
    ###
    - role: mergerfs
      tags:
        - mergerfs
      when: (mergerfs_enabled | default(False))

    ###
    ### snapRAID
    ###
    - role: snapraid
      tags:
        - snapraid
      when: (snapraid_enabled | default(False))

    ###
    ### snapRAID cron scheduling
    ###
    - role: cron-snapraid
      tags:
        - cron
        - cron-snapraid
        - snapraid-cron
        - snapraid-scheduling
      when: (snapraid_cron_enabled | default(False))