---
- name: Create group for new admin user
  group:
    name: "{{ admin_username }}"
    state: present

- name: Create new admin user 
  user:
    name: "{{ admin_username }}"
    state: present
    uid: 990
    system: yes
    update_password: on_create
    create_home: no
    group: "{{ admin_username }}"
    shell: /usr/sbin/nologin
